# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "apps/web/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ">=13.7"
      - name: npm install
        run: npm install
      - name: Build
        run: BASE_URL=http://localhost:3000 npm run build
