name: reviewdog
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install --legacy-peer-deps
      - name: eslint
        run: npm rum lint
      - name: format
        run: npm run format
