name: deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: npm install
      - name: build packages
        run: npm run build -w packages/models
      - name: build storybook
        run: npm run build-storybook -w apps/web
      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: apps/web/build
